from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('master-requests/', views.master_requests_list, name='master_requests_list'),
    path('master-request/<int:request_id>/', views.master_request_detail, name='master_request_detail'),
    path('catalog/', views.catalog_view, name='catalog'),
    path('masterclass/<int:pk>/', views.masterclass_detail, name='masterclass_detail'),
    path('masterclass/<int:pk>/add_review/', views.add_review, name='add_review'),
    path('confirm/<str:token>/', views.confirm_signup, name='confirm_signup'),
    path('profile/', views.profile_view, name='profile'),
    path('master/<int:user_id>/', views.master_profile, name='master_profile'),
    path('privacy/', views.privacy, name='privacy'),
    path('create-masterclass/', views.create_masterclass, name='create_masterclass'),
    path('manage-signups/', views.manage_signups, name='manage_signups'),
    path('signup/<int:signup_id>/change-status/', views.change_signup_status, name='change_signup_status'),
    path('moderate-masterclasses/', views.moderate_masterclasses, name='moderate_masterclasses'),
    path('master/<int:user_id>/reviews/', views.master_reviews, name='master_reviews'),
    path('moderate-masterclass/<int:pk>/', views.moderate_masterclass_detail, name='moderate_masterclass_detail'),
    path('masterclass/<int:masterclass_id>/sessions/', views.manage_sessions, name='manage_sessions'),
    path('session/<int:session_id>/edit/', views.edit_session, name='edit_session'),
    path('session/<int:session_id>/delete/', views.delete_session, name='delete_session'),
    path('moderate-signups/', views.moderate_signups, name='moderate_signups'),
    path('moderate-signup/<int:signup_id>/', views.moderate_signup_detail, name='moderate_signup_detail'),
    path('signup/<int:signup_id>/mark-attended/', views.mark_attended, name='mark_attended'),
    path('notifications/mark-read/', views.mark_notifications_read, name='mark_notifications_read'),
]