# Generated by Django 6.0.2 on 2026-02-16 20:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название роли')),
            ],
        ),
        migrations.CreateModel(
            name='MasterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название мастер-класса')),
                ('description', models.TextField(verbose_name='Описание')),
                ('count', models.PositiveIntegerField(verbose_name='Количество доступных мест')),
                ('date_event', models.DateField(verbose_name='Дата проведения')),
                ('time_event', models.TimeField(blank=True, null=True, verbose_name='Время начала')),
                ('duration', models.CharField(max_length=255, verbose_name='Продолжительность')),
                ('format', models.IntegerField(choices=[(1, 'Онлайн'), (2, 'Очная встреча')], verbose_name='Формат мероприятия')),
                ('method_payment', models.IntegerField(choices=[(1, 'Банковская карта'), (2, 'Онлайн перевод')], verbose_name='Способ оплаты')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Стоимость')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('status', models.IntegerField(choices=[(1, 'Черновик'), (2, 'На модерации'), (3, 'Опубликован'), (4, 'Идёт проведение'), (5, 'Завершён'), (6, 'Отклонён')], default=1, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория')),
                ('master', models.ForeignKey(blank=True, limit_choices_to={'profile__role__name': 'Мастер'}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Мастер')),
            ],
        ),
        migrations.CreateModel(
            name='MasterRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.IntegerField(choices=[(1, 'На рассмотрении'), (2, 'Одобрена'), (3, 'Отклонена')], default=1, verbose_name='Статус')),
                ('admin_comment', models.TextField(blank=True, verbose_name='Комментарий администратора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_requests', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.role', verbose_name='Роль')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст отзыва')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Оценка от 1 до 5')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания отзыва')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('masterclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.masterclass', verbose_name='Мастер-класс')),
            ],
            options={
                'unique_together': {('client', 'masterclass')},
            },
        ),
        migrations.CreateModel(
            name='SignUpClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата подачи')),
                ('status', models.IntegerField(choices=[(1, 'Активна'), (2, 'Отменена'), (3, 'Посещено')], default=1, verbose_name='Статус')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SignUpClass', to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('masterclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SignUpClass', to='main.masterclass', verbose_name='Мастер-класс')),
            ],
            options={
                'unique_together': {('client', 'masterclass')},
            },
        ),
    ]
