# Generated by Django 6.0 on 2026-03-09 13:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterclass',
            name='duration',
        ),
        migrations.AddField(
            model_name='masterclass',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес'),
        ),
        migrations.AddField(
            model_name='masterclass',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=60, verbose_name='Длительность (мин)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='masterclass',
            name='show_on_home',
            field=models.BooleanField(default=False, verbose_name='Показывать на главной'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='bio',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='signupclass',
            name='confirmation_token',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='count',
            field=models.PositiveIntegerField(verbose_name='Количество мест'),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='format',
            field=models.IntegerField(choices=[(1, 'Онлайн'), (2, 'Очная встреча')], verbose_name='Формат'),
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='master',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='masterclasses', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='masterclass',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='masterrequest',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='masterrequest',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий клиента'),
        ),
        migrations.AlterField(
            model_name='masterrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='masterrequest',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='masterrequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'На рассмотрении'), (2, 'Одобрена'), (3, 'Отклонена')], default=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='masterclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='main.masterclass'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='signupclass',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='signupclass',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='signupclass',
            name='masterclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='main.masterclass'),
        ),
        migrations.AlterField(
            model_name='signupclass',
            name='status',
            field=models.IntegerField(choices=[(1, 'Ожидает подтверждения'), (2, 'Подтверждена'), (3, 'Отменена'), (4, 'Посещено')], default=1),
        ),
        migrations.CreateModel(
            name='MasterClassImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='masterclass_images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('masterclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.masterclass')),
            ],
        ),
    ]
