# Generated by Django 4.2.29 on 2026-03-11 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_alter_category_id_alter_masterclass_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterclass',
            name='count',
        ),
        migrations.RemoveField(
            model_name='masterclass',
            name='date_event',
        ),
        migrations.RemoveField(
            model_name='masterclass',
            name='time_event',
        ),
        migrations.AddField(
            model_name='signupclass',
            name='master_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий мастера'),
        ),
        migrations.AlterField(
            model_name='signupclass',
            name='status',
            field=models.IntegerField(choices=[(1, 'Ожидает подтверждения'), (2, 'Подтверждена (ожидает решения мастера)'), (3, 'Одобрена мастером'), (4, 'Отменена'), (5, 'Посещено')], default=1),
        ),
        migrations.CreateModel(
            name='MasterClassDateTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_event', models.DateField(verbose_name='Дата проведения')),
                ('time_event', models.TimeField(verbose_name='Время начала')),
                ('count', models.PositiveIntegerField(verbose_name='Количество мест')),
                ('booked', models.PositiveIntegerField(default=0, verbose_name='Занято мест')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('masterclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='main.masterclass')),
            ],
            options={
                'ordering': ['date_event', 'time_event'],
                'unique_together': {('masterclass', 'date_event', 'time_event')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='signupclass',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='signupclass',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='main.masterclassdatetime'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='signupclass',
            unique_together={('client', 'session')},
        ),
        migrations.RemoveField(
            model_name='signupclass',
            name='masterclass',
        ),
    ]
