# Generated by Django 4.2.29 on 2026-03-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupclass',
            name='confirmation_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
